[application]
name = "BrewFlow"
default_platform = "web"

[web.app]
title = "BrewFlow - Offline Retail & Training Suite"
base_path = ""

[web.watcher]
watch_path = ["src", "shared"]
reload_html = true

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
